---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: node-exporter-resizer
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  resourceNames: ["node-exporter"]
  verbs: ["get", "update"]

