apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    k8s-app: frontend
spec:
  selector:
    matchLabels:
      k8s-app: example-app
  endpoints:
  - port: web